### Require REST Client VSCode Extenction to run
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Variables
@url=http://localhost:5000
@token=token



### Search Jobs
GET {{url}}/search/developer?city=tirane&type=0&jobDate=10 HTTP/1.1


### Register User
POST {{url}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "name":"user",
    "email":"example@example.com",
    "password":"xxxxx",
    "jobTitle":"xxxxx"
}

### Verify Account
GET {{url}}/auth/verify/token HTTP/1.1


### Login User
POST {{url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"example@example.com",
    "password":"xxxxx"
}


### Delete User
DELETE {{url}}/auth/remove HTTP/1.1
Authorization: Bearer {{token}}


### Get User Detail
GET {{url}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Update User Detail
PUT {{url}}/auth/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "jobCity":"xxxxx",
    "jobType":1
}

### Update User Password
PUT {{url}}/auth/update/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currentPassword":"xxxxx",
    "newPassword":"xxxxx"
}

### Get User Jobs
GET {{url}}/auth/jobs HTTP/1.1
Authorization: Bearer {{token}}


### Bookmark Job
POST {{url}}/auth/bookmark HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "xxxxx",
    "link": "xxxxx"
}


### Get Bookmark
GET {{url}}/auth/bookmark HTTP/1.1
Authorization: Bearer {{token}}


### Check if Job is Bookmarked
POST {{url}}/auth/bookmark/check HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "link":"xxxxx"
}


### Forgot Password
POST {{url}}/auth/forgotpassword HTTP/1.1
Content-Type: application/json

{
    "email":"example@example.com"
}

### Reset Password
PUT {{url}}/auth/resetpassword/:resetToken HTTP/1.1
Content-Type: application/json

{
    "password":"xxxxx"
}

